In [136]:
# 라이브러리 다운로드
!pip install pandas numpy matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.3.3)
Requirement already satisfied: numpy in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.3.5)
Requirement already satisfied: matplotlib in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.10.8)
Requirement already satisfied: seaborn in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\zkzkf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\zkzkf\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [137]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

In [138]:
from pathlib import Path

print(Path.cwd())

c:\Users\zkzkf\OneDrive\바탕 화면\cafe_startup_analysis\01_area_selection\notebooks

In [139]:
# 데이터 불러오기
from pathlib import Path

data_path = Path("../data/raw/20262Q_소규모.csv")
s_store_2026_2 = pd.read_csv(data_path, encoding="cp949")

data_path = Path("../data/raw/20262Q_중대형.csv")
b_store_2026_2 = pd.read_csv(data_path, encoding="cp949")

data_path = Path("../data/raw/20262Q_집합.csv")
g_store_2026_2 = pd.read_csv(data_path, encoding="cp949")

C:\Users\zkzkf\AppData\Local\Temp\ipykernel_9204\139264082.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  s_store_2026_2 = pd.read_csv(data_path, encoding="cp949")
C:\Users\zkzkf\AppData\Local\Temp\ipykernel_9204\139264082.py:8: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  b_store_2026_2 = pd.read_csv(data_path, encoding="cp949")
C:\Users\zkzkf\AppData\Local\Temp\ipykernel_9204\139264082.py:11: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  g_store_2026_2 = pd.read_csv(data_path, encoding="cp949")

In [140]:
print(s_store_2026_2.shape, b_store_2026_2.shape, g_store_2026_2.shape)

(11344, 76) (29733, 76) (29500, 61)

In [141]:
s_store_2026_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11344 entries, 0 to 11343
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   조사분기              11344 non-null  int64
 1   표본구분              11344 non-null  int64
 2   광역상권              2038 non-null   object
 3   상권명               11344 non-null  object
 4   시군구코드             11344 non-null  int64
 5   용도지역1명            11344 non-null  int64
 6   용도지역2명            11344 non-null  int64
 7   용도지구1명            11344 non-null  int64
 8   용도지구2명            11344 non-null  int64
 9   이용현황_지상층수         11344 non-null  int64
 10  이용현황_지하층수         11344 non-null  int64
 11  사용승인일자            11344 non-null  int64
 12  건물구조명             11344 non-null  int64
 13  건물주용도             11344 non-null  int64
 14  건폐율               11344 non-null  int64
 15  용적률               11344 non-null  int64
 16  지하철역출구            11344 non-null  object
 17  버스정류장             11344 non-null  object
 18  도로접면명             11344 non-null  int64
 19  옥내주차장 유무명         11344 non-null  int64
 20  옥외주차장 유무명         11344 non-null  int64
 21  승객용 승강기           11344 non-null  int64
 22  대지면적              11344 non-null  int64
 23  건축연면적             11344 non-null  int64
 24  전용면적              11344 non-null  int64
 25  공용면적              11344 non-null  int64
 26  전용률               11344 non-null  int64
 27  현재임대계약면적          11344 non-null  int64
 28  공실면적              11344 non-null  int64
 29  비임대면적             11344 non-null  int64
 30  특이면적              11344 non-null  int64
 31  특이면적외 기타면적        11344 non-null  int64
 32  지목명               11344 non-null  int64
 33  토지대장상 토지면적        11344 non-null  int64
 34  전환률               11344 non-null  int64
 35  조사층               11344 non-null  int64
 36  임차인사용현황구분         11344 non-null  int64
 37  임차인업종대분류          11344 non-null  object
 38  임차인업종소분류          11344 non-null  int64
 39  전용면적(호)           11344 non-null  int64
 40  공용면적(호)           11344 non-null  int64
 41  임차인별면적합계          11344 non-null  int64
 42  제1월계약임대료_보증금      11344 non-null  int64
 43  제1월계약임대료_월세       11344 non-null  int64
 44  제1월계약임대료_㎡당환산임대료  11344 non-null  int64
 45  제1월시장임대료_보증금      11344 non-null  int64
 46  제1월시장임대료_월세       11344 non-null  int64
 47  제1월시장임대료_㎡당환산임대료  11344 non-null  int64
 48  제1월관리비총액          11344 non-null  int64
 49  제1월관리비실비총액        11344 non-null  int64
 50  제1월공실             11344 non-null  int64
 51  제2월계약임대료_보증금      11344 non-null  int64
 52  제2월계약임대료_월세       11344 non-null  int64
 53  제2월계약임대료_㎡당환산임대료  11344 non-null  int64
 54  제2월시장임대료_보증금      11344 non-null  int64
 55  제2월시장임대료_월세       11344 non-null  int64
 56  제2월시장임대료_㎡당환산임대료  11344 non-null  int64
 57  제2월관리비총액          11344 non-null  int64
 58  제2월관리비실비총액        11344 non-null  int64
 59  제2월공실             11344 non-null  int64
 60  제3월계약임대료_보증금      11344 non-null  int64
 61  제3월계약임대료_월세       11344 non-null  int64
 62  제3월계약임대료_㎡당환산임대료  11344 non-null  int64
 63  제3월시장임대료_보증금      11344 non-null  int64
 64  제3월시장임대료_월세       11344 non-null  int64
 65  제3월시장임대료_㎡당환산임대료  11344 non-null  int64
 66  제3월관리비총액          11344 non-null  int64
 67  제3월관리비실비총액        11344 non-null  int64
 68  제3월공실             11344 non-null  int64
 69  현계약개시일            11344 non-null  int64
 70  현계약기간             11344 non-null  int64
 71  최초계약개시일           11344 non-null  int64
 72  최종조사산정액_토지면적 ㎡단가  11344 non-null  int64
 73  최종조사산정액_연면적 ㎡당단가  11344 non-null  int64
 74  기타수입_연면적 ㎡당 단가    11344 non-null  int64
 75  영업경비_연면적 ㎡당 단가    11344 non-null  int64
dtypes: int64(71), object(5)
memory usage: 6.6+ MB

In [142]:
b_store_2026_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29733 entries, 0 to 29732
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   조사분기              29733 non-null  int64
 1   표본구분              29733 non-null  int64
 2   광역상권              8765 non-null   object
 3   상권명               29733 non-null  object
 4   시군구코드             29733 non-null  int64
 5   용도지역1명            29733 non-null  int64
 6   용도지역2명            29733 non-null  int64
 7   용도지구1명            29733 non-null  int64
 8   용도지구2명            29733 non-null  int64
 9   이용현황_지상층수         29733 non-null  int64
 10  이용현황_지하층수         29733 non-null  int64
 11  사용승인일자            29733 non-null  int64
 12  건물구조명             29733 non-null  int64
 13  건물주용도             29733 non-null  int64
 14  건폐율               29733 non-null  int64
 15  용적률               29733 non-null  int64
 16  지하철역출구            29733 non-null  object
 17  버스정류장             29733 non-null  object
 18  도로접면명             29733 non-null  int64
 19  옥내주차장 유무명         29733 non-null  int64
 20  옥외주차장 유무명         29733 non-null  int64
 21  승객용 승강기           29733 non-null  int64
 22  대지면적              29733 non-null  int64
 23  건축연면적             29733 non-null  int64
 24  전용면적              29733 non-null  int64
 25  공용면적              29733 non-null  int64
 26  전용률               29733 non-null  int64
 27  현재임대계약면적          29733 non-null  int64
 28  공실면적              29733 non-null  int64
 29  비임대면적             29733 non-null  int64
 30  특이면적              29733 non-null  int64
 31  특이면적외 기타면적        29733 non-null  int64
 32  지목명               29733 non-null  int64
 33  토지대장상 토지면적        29733 non-null  int64
 34  전환률               29733 non-null  int64
 35  조사층               29733 non-null  int64
 36  임차인사용현황구분         29733 non-null  int64
 37  임차인업종대분류          29733 non-null  object
 38  임차인업종소분류          29733 non-null  int64
 39  전용면적(호)           29733 non-null  int64
 40  공용면적(호)           29733 non-null  int64
 41  임차인별면적합계          29733 non-null  int64
 42  제1월계약임대료_보증금      29733 non-null  int64
 43  제1월계약임대료_월세       29733 non-null  int64
 44  제1월계약임대료_㎡당환산임대료  29733 non-null  int64
 45  제1월시장임대료_보증금      29733 non-null  int64
 46  제1월시장임대료_월세       29733 non-null  int64
 47  제1월시장임대료_㎡당환산임대료  29733 non-null  int64
 48  제1월관리비총액          29733 non-null  int64
 49  제1월관리비실비총액        29733 non-null  int64
 50  제1월공실             29733 non-null  int64
 51  제2월계약임대료_보증금      29733 non-null  int64
 52  제2월계약임대료_월세       29733 non-null  int64
 53  제2월계약임대료_㎡당환산임대료  29733 non-null  int64
 54  제2월시장임대료_보증금      29733 non-null  int64
 55  제2월시장임대료_월세       29733 non-null  int64
 56  제2월시장임대료_㎡당환산임대료  29733 non-null  int64
 57  제2월관리비총액          29733 non-null  int64
 58  제2월관리비실비총액        29733 non-null  int64
 59  제2월공실             29733 non-null  int64
 60  제3월계약임대료_보증금      29733 non-null  int64
 61  제3월계약임대료_월세       29733 non-null  int64
 62  제3월계약임대료_㎡당환산임대료  29733 non-null  int64
 63  제3월시장임대료_보증금      29733 non-null  int64
 64  제3월시장임대료_월세       29733 non-null  int64
 65  제3월시장임대료_㎡당환산임대료  29733 non-null  int64
 66  제3월관리비총액          29733 non-null  int64
 67  제3월관리비실비총액        29733 non-null  int64
 68  제3월공실             29733 non-null  int64
 69  현계약개시일            29733 non-null  int64
 70  현계약기간             29733 non-null  int64
 71  최초계약개시일           29733 non-null  int64
 72  최종조사산정액_토지면적 ㎡단가  29733 non-null  int64
 73  최종조사산정액_연면적 ㎡당단가  29733 non-null  int64
 74  기타수입_연면적 ㎡당 단가    29733 non-null  int64
 75  영업경비_연면적 ㎡당 단가    29733 non-null  int64
dtypes: int64(71), object(5)
memory usage: 17.2+ MB

In [143]:
g_store_2026_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29500 entries, 0 to 29499
Data columns (total 61 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   조사분기              29500 non-null  int64
 1   광역상권              5604 non-null   object
 2   상권명               29500 non-null  object
 3   시군구코드             29500 non-null  int64
 4   대지면적              29500 non-null  int64
 5   건축면적              29500 non-null  int64
 6   건축연면적             29500 non-null  int64
 7   건폐율               29500 non-null  int64
 8   용적률               29500 non-null  int64
 9   건물구조              29500 non-null  int64
 10  건물주용도             29500 non-null  int64
 11  이용현황_지상층수         29500 non-null  int64
 12  이용현황_지하층수         29500 non-null  int64
 13  사용승인일자            29500 non-null  int64
 14  승강기수              29500 non-null  int64
 15  용도지역              29500 non-null  int64
 16  지하철역출구            29500 non-null  object
 17  버스정류장             29500 non-null  object
 18  전환률               29500 non-null  int64
 19  전통시장              29500 non-null  int64
 20  기준층               29500 non-null  int64
 21  조사층               29500 non-null  int64
 22  임차인사용현황구분         29500 non-null  int64
 23  임차인업종대분류          29500 non-null  object
 24  임차인업종소분류          29500 non-null  int64
 25  전용면적(호)           29500 non-null  int64
 26  공용면적(호)           29500 non-null  int64
 27  임차인별면적합계          29500 non-null  int64
 28  제1월계약임대료_보증금      29500 non-null  int64
 29  제1월계약임대료_월세       29500 non-null  int64
 30  제1월계약임대료_㎡당환산임대료  29500 non-null  int64
 31  제1월시장임대료_보증금      29500 non-null  int64
 32  제1월시장임대료_월세       29500 non-null  int64
 33  제1월시장임대료_㎡당환산임대료  29500 non-null  int64
 34  제1월관리비총액          29500 non-null  int64
 35  제1월관리비실비총액        29500 non-null  int64
 36  제1월공실             29500 non-null  int64
 37  제2월계약임대료_보증금      29500 non-null  int64
 38  제2월계약임대료_월세       29500 non-null  int64
 39  제2월계약임대료_㎡당환산임대료  29500 non-null  int64
 40  제2월시장임대료_보증금      29500 non-null  int64
 41  제2월시장임대료_월세       29500 non-null  int64
 42  제2월시장임대료_㎡당환산임대료  29500 non-null  int64
 43  제2월관리비총액          29500 non-null  int64
 44  제2월관리비실비총액        29500 non-null  int64
 45  제2월공실             29500 non-null  int64
 46  제3월계약임대료_보증금      29500 non-null  int64
 47  제3월계약임대료_월세       29500 non-null  int64
 48  제3월계약임대료_㎡당환산임대료  29500 non-null  int64
 49  제3월시장임대료_보증금      29500 non-null  int64
 50  제3월시장임대료_월세       29500 non-null  int64
 51  제3월시장임대료_㎡당환산임대료  29500 non-null  int64
 52  제3월관리비총액          29500 non-null  int64
 53  제3월관리비실비총액        29500 non-null  int64
 54  제3월공실             29500 non-null  int64
 55  현계약개시일            29500 non-null  int64
 56  현계약기간             29500 non-null  int64
 57  최초계약개시일           29500 non-null  int64
 58  최종조사산정액_㎡당 단가     29500 non-null  int64
 59  기타수입_㎡당 단가        29500 non-null  int64
 60  영업경비_㎡당 단가        29500 non-null  int64
dtypes: int64(56), object(5)
memory usage: 13.7+ MB

In [144]:
display(s_store_2026_2.isna().sum(), b_store_2026_2.isna().sum(), g_store_2026_2.isna().sum())  # 세 데이터프레임 모두 광역상권에 결측치가 있다.

조사분기                   0
표본구분                   0
광역상권                9306
상권명                    0
시군구코드                  0
용도지역1명                 0
용도지역2명                 0
용도지구1명                 0
용도지구2명                 0
이용현황_지상층수              0
이용현황_지하층수              0
사용승인일자                 0
건물구조명                  0
건물주용도                  0
건폐율                    0
용적률                    0
지하철역출구                 0
버스정류장                  0
도로접면명                  0
옥내주차장 유무명              0
옥외주차장 유무명              0
승객용 승강기                0
대지면적                   0
건축연면적                  0
전용면적                   0
공용면적                   0
전용률                    0
현재임대계약면적               0
공실면적                   0
비임대면적                  0
특이면적                   0
특이면적외 기타면적             0
지목명                    0
토지대장상 토지면적             0
전환률                    0
조사층                    0
임차인사용현황구분              0
임차인업종대분류               0
임차인업종소분류               0
전용면적(호)                0
공용면적(호)                0
임차인별면적합계               0
제1월계약임대료_보증금           0
제1월계약임대료_월세            0
제1월계약임대료_㎡당환산임대료       0
제1월시장임대료_보증금           0
제1월시장임대료_월세            0
제1월시장임대료_㎡당환산임대료       0
제1월관리비총액               0
제1월관리비실비총액             0
제1월공실                  0
제2월계약임대료_보증금           0
제2월계약임대료_월세            0
제2월계약임대료_㎡당환산임대료       0
제2월시장임대료_보증금           0
제2월시장임대료_월세            0
제2월시장임대료_㎡당환산임대료       0
제2월관리비총액               0
제2월관리비실비총액             0
제2월공실                  0
제3월계약임대료_보증금           0
제3월계약임대료_월세            0
제3월계약임대료_㎡당환산임대료       0
제3월시장임대료_보증금           0
제3월시장임대료_월세            0
제3월시장임대료_㎡당환산임대료       0
제3월관리비총액               0
제3월관리비실비총액             0
제3월공실                  0
현계약개시일                 0
현계약기간                  0
최초계약개시일                0
최종조사산정액_토지면적 ㎡단가       0
최종조사산정액_연면적 ㎡당단가       0
기타수입_연면적 ㎡당 단가         0
영업경비_연면적 ㎡당 단가         0
dtype: int64

조사분기                    0
표본구분                    0
광역상권                20968
상권명                     0
시군구코드                   0
용도지역1명                  0
용도지역2명                  0
용도지구1명                  0
용도지구2명                  0
이용현황_지상층수               0
이용현황_지하층수               0
사용승인일자                  0
건물구조명                   0
건물주용도                   0
건폐율                     0
용적률                     0
지하철역출구                  0
버스정류장                   0
도로접면명                   0
옥내주차장 유무명               0
옥외주차장 유무명               0
승객용 승강기                 0
대지면적                    0
건축연면적                   0
전용면적                    0
공용면적                    0
전용률                     0
현재임대계약면적                0
공실면적                    0
비임대면적                   0
특이면적                    0
특이면적외 기타면적              0
지목명                     0
토지대장상 토지면적              0
전환률                     0
조사층                     0
임차인사용현황구분               0
임차인업종대분류                0
임차인업종소분류                0
전용면적(호)                 0
공용면적(호)                 0
임차인별면적합계                0
제1월계약임대료_보증금            0
제1월계약임대료_월세             0
제1월계약임대료_㎡당환산임대료        0
제1월시장임대료_보증금            0
제1월시장임대료_월세             0
제1월시장임대료_㎡당환산임대료        0
제1월관리비총액                0
제1월관리비실비총액              0
제1월공실                   0
제2월계약임대료_보증금            0
제2월계약임대료_월세             0
제2월계약임대료_㎡당환산임대료        0
제2월시장임대료_보증금            0
제2월시장임대료_월세             0
제2월시장임대료_㎡당환산임대료        0
제2월관리비총액                0
제2월관리비실비총액              0
제2월공실                   0
제3월계약임대료_보증금            0
제3월계약임대료_월세             0
제3월계약임대료_㎡당환산임대료        0
제3월시장임대료_보증금            0
제3월시장임대료_월세             0
제3월시장임대료_㎡당환산임대료        0
제3월관리비총액                0
제3월관리비실비총액              0
제3월공실                   0
현계약개시일                  0
현계약기간                   0
최초계약개시일                 0
최종조사산정액_토지면적 ㎡단가        0
최종조사산정액_연면적 ㎡당단가        0
기타수입_연면적 ㎡당 단가          0
영업경비_연면적 ㎡당 단가          0
dtype: int64

조사분기                    0
광역상권                23896
상권명                     0
시군구코드                   0
대지면적                    0
건축면적                    0
건축연면적                   0
건폐율                     0
용적률                     0
건물구조                    0
건물주용도                   0
이용현황_지상층수               0
이용현황_지하층수               0
사용승인일자                  0
승강기수                    0
용도지역                    0
지하철역출구                  0
버스정류장                   0
전환률                     0
전통시장                    0
기준층                     0
조사층                     0
임차인사용현황구분               0
임차인업종대분류                0
임차인업종소분류                0
전용면적(호)                 0
공용면적(호)                 0
임차인별면적합계                0
제1월계약임대료_보증금            0
제1월계약임대료_월세             0
제1월계약임대료_㎡당환산임대료        0
제1월시장임대료_보증금            0
제1월시장임대료_월세             0
제1월시장임대료_㎡당환산임대료        0
제1월관리비총액                0
제1월관리비실비총액              0
제1월공실                   0
제2월계약임대료_보증금            0
제2월계약임대료_월세             0
제2월계약임대료_㎡당환산임대료        0
제2월시장임대료_보증금            0
제2월시장임대료_월세             0
제2월시장임대료_㎡당환산임대료        0
제2월관리비총액                0
제2월관리비실비총액              0
제2월공실                   0
제3월계약임대료_보증금            0
제3월계약임대료_월세             0
제3월계약임대료_㎡당환산임대료        0
제3월시장임대료_보증금            0
제3월시장임대료_월세             0
제3월시장임대료_㎡당환산임대료        0
제3월관리비총액                0
제3월관리비실비총액              0
제3월공실                   0
현계약개시일                  0
현계약기간                   0
최초계약개시일                 0
최종조사산정액_㎡당 단가           0
기타수입_㎡당 단가              0
영업경비_㎡당 단가              0
dtype: int64

In [145]:
s_store_2026_2.columns

Index(['조사분기', '표본구분', '광역상권', '상권명', '시군구코드', '용도지역1명', '용도지역2명', '용도지구1명',
       '용도지구2명', '이용현황_지상층수', '이용현황_지하층수', '사용승인일자', '건물구조명', '건물주용도', '건폐율',
       '용적률', '지하철역출구', '버스정류장', '도로접면명', '옥내주차장 유무명', '옥외주차장 유무명', '승객용 승강기',
       '대지면적', '건축연면적', '전용면적', '공용면적', '전용률', '현재임대계약면적', '공실면적', '비임대면적',
       '특이면적', '특이면적외 기타면적', '지목명', '토지대장상 토지면적', '전환률', '조사층', '임차인사용현황구분',
       '임차인업종대분류', '임차인업종소분류', '전용면적(호)', '공용면적(호)', '임차인별면적합계',
       '제1월계약임대료_보증금', '제1월계약임대료_월세', '제1월계약임대료_㎡당환산임대료', '제1월시장임대료_보증금',
       '제1월시장임대료_월세', '제1월시장임대료_㎡당환산임대료', '제1월관리비총액', '제1월관리비실비총액', '제1월공실',
       '제2월계약임대료_보증금', '제2월계약임대료_월세', '제2월계약임대료_㎡당환산임대료', '제2월시장임대료_보증금',
       '제2월시장임대료_월세', '제2월시장임대료_㎡당환산임대료', '제2월관리비총액', '제2월관리비실비총액', '제2월공실',
       '제3월계약임대료_보증금', '제3월계약임대료_월세', '제3월계약임대료_㎡당환산임대료', '제3월시장임대료_보증금',
       '제3월시장임대료_월세', '제3월시장임대료_㎡당환산임대료', '제3월관리비총액', '제3월관리비실비총액', '제3월공실',
       '현계약개시일', '현계약기간', '최초계약개시일', '최종조사산정액_토지면적 ㎡단가', '최종조사산정액_연면적 ㎡당단가',
       '기타수입_연면적 ㎡당 단가', '영업경비_연면적 ㎡당 단가'],
      dtype='object')

In [146]:
b_store_2026_2.columns

Index(['조사분기', '표본구분', '광역상권', '상권명', '시군구코드', '용도지역1명', '용도지역2명', '용도지구1명',
       '용도지구2명', '이용현황_지상층수', '이용현황_지하층수', '사용승인일자', '건물구조명', '건물주용도', '건폐율',
       '용적률', '지하철역출구', '버스정류장', '도로접면명', '옥내주차장 유무명', '옥외주차장 유무명', '승객용 승강기',
       '대지면적', '건축연면적', '전용면적', '공용면적', '전용률', '현재임대계약면적', '공실면적', '비임대면적',
       '특이면적', '특이면적외 기타면적', '지목명', '토지대장상 토지면적', '전환률', '조사층', '임차인사용현황구분',
       '임차인업종대분류', '임차인업종소분류', '전용면적(호)', '공용면적(호)', '임차인별면적합계',
       '제1월계약임대료_보증금', '제1월계약임대료_월세', '제1월계약임대료_㎡당환산임대료', '제1월시장임대료_보증금',
       '제1월시장임대료_월세', '제1월시장임대료_㎡당환산임대료', '제1월관리비총액', '제1월관리비실비총액', '제1월공실',
       '제2월계약임대료_보증금', '제2월계약임대료_월세', '제2월계약임대료_㎡당환산임대료', '제2월시장임대료_보증금',
       '제2월시장임대료_월세', '제2월시장임대료_㎡당환산임대료', '제2월관리비총액', '제2월관리비실비총액', '제2월공실',
       '제3월계약임대료_보증금', '제3월계약임대료_월세', '제3월계약임대료_㎡당환산임대료', '제3월시장임대료_보증금',
       '제3월시장임대료_월세', '제3월시장임대료_㎡당환산임대료', '제3월관리비총액', '제3월관리비실비총액', '제3월공실',
       '현계약개시일', '현계약기간', '최초계약개시일', '최종조사산정액_토지면적 ㎡단가', '최종조사산정액_연면적 ㎡당단가',
       '기타수입_연면적 ㎡당 단가', '영업경비_연면적 ㎡당 단가'],
      dtype='object')

In [147]:
g_store_2026_2.columns

Index(['조사분기', '광역상권', '상권명', '시군구코드', '대지면적', '건축면적', '건축연면적', '건폐율', '용적률',
       '건물구조', '건물주용도', '이용현황_지상층수', '이용현황_지하층수', '사용승인일자', '승강기수', '용도지역',
       '지하철역출구', '버스정류장', '전환률', '전통시장', '기준층', '조사층', '임차인사용현황구분', '임차인업종대분류',
       '임차인업종소분류', '전용면적(호)', '공용면적(호)', '임차인별면적합계', '제1월계약임대료_보증금',
       '제1월계약임대료_월세', '제1월계약임대료_㎡당환산임대료', '제1월시장임대료_보증금', '제1월시장임대료_월세',
       '제1월시장임대료_㎡당환산임대료', '제1월관리비총액', '제1월관리비실비총액', '제1월공실', '제2월계약임대료_보증금',
       '제2월계약임대료_월세', '제2월계약임대료_㎡당환산임대료', '제2월시장임대료_보증금', '제2월시장임대료_월세',
       '제2월시장임대료_㎡당환산임대료', '제2월관리비총액', '제2월관리비실비총액', '제2월공실', '제3월계약임대료_보증금',
       '제3월계약임대료_월세', '제3월계약임대료_㎡당환산임대료', '제3월시장임대료_보증금', '제3월시장임대료_월세',
       '제3월시장임대료_㎡당환산임대료', '제3월관리비총액', '제3월관리비실비총액', '제3월공실', '현계약개시일',
       '현계약기간', '최초계약개시일', '최종조사산정액_㎡당 단가', '기타수입_㎡당 단가', '영업경비_㎡당 단가'],
      dtype='object')

In [148]:
g_store_2026_2['상권명'].unique()  # 성수/뚝섬 관련 데이터가 없다. 따라서 집합상가 데이터는 분석에서 제외한다.

array(['0.비상권', '강릉중부', '동해천곡', '삼척중앙시장', '속초중앙시장', '영월경찰서', '원주무실지구',
       '원주중앙/일산', '원주혁신도시', '춘천명동', '태백중앙시장', '고양시청', '고잔신도시', '광교중앙역',
       '광명철산', '금릉역', '김포운양역', '김포장기역', '김포한강구래', '남양주다산', '남양주별내',
       '동백지구', '동탄2신도시', '동탄센트럴파크', '모란', '미사지구', '배곧신도시', '범계학원가', '병점역',
       '부천역', '분당역세권', '산본역', '상록수역', '상중동', '상현역', '서판교', '선부다이아몬드',
       '성남구시가지', '송내역', '수원역', '시흥시립도서관', '안산중앙역', '안성 서인사거리', '안양역',
       '야탑역', '역곡역', '오산시청', '용인수지', '월피다이아몬드', '위례신도시', '의정부민락', '의정부역',
       '이천종합터미널', '인계동', '일산라페스타', '죽전카페거리', '탄현역', '파주시청', '파주야당역',
       '파주운정호수', '팔달문로터리', '평촌범계', '평택역', '한대앞역', '행신역', '화정역', '거제고현',
       '거제옥포', '김해수리공원', '김해시 내외동', '김해시청/동상시장', '김해장유', '마산동서동',
       '마산역버스터미널', '물금지구', '양산구도심', '양산역', '진주혁신도시', '진해석동', '창원명곡동',
       '창원시청', '창원역', '창원월영동', '창원의창구청', '활천동', '경북김천혁신도시', '경북도청신도시',
       '구미산업단지', '구미역', '문경점촌흥덕', '안동구도심', '영주중앙', '옥동사거리', '포항원도심',
       '포항중앙', '금남로/충장로', '봉선동', '상무지구', '송정동지구', '수완지구', '첨단1지구',
       '첨단2지구', '계명대', '대구혁신도시', '동성로중심', '두류감삼역', '상인/월배', '서문시장/청라언덕',
       '수성범어', '시지지구', '이시아폴리스', '죽전역', '칠곡', '현풍테크노폴리스', '가수원', '노은',
       '대전동구청', '동춘당공원', '둔산', '목원대', '유성온천역', '광안리', '남포동', '동래역',
       '명지국제도시', '명지오션시티', '민락공원', '부전시장', '사상역', '서면/전포', '센텀마린시티',
       '연산로터리', '온천장', '정관신도시', '해운대', '현대백화점주변', '화명역', '남대문', '동대문',
       '방산시장', '종로', '강남대로', '교대역', '남부터미널', '논현역', '도산대로', '신사역', '압구정',
       '청담', '테헤란로', '한티역', '당산역', '신촌/이대', '여의도', '영등포역', '홍대/합정',
       '가락시장', '건대입구', '노원역', '명일역', '목동', '불광역', '사당', '서울대입구역', '성신여대',
       '수유', '숙명여대', '신림역', '오류동역', '용산역', '잠실/송파', '잠실새내역', '장안동', '천호',
       '청량리', '혜화동', '화곡', '나성한솔동', '세종정부청사', '삼산동', '성남옥교동', '신정동',
       '울산농소', '전하동', '간석오거리', '계양계산', '구월', '부평', '송도', '신포동', '영종',
       '인천논현역', '주안', '청라국제도시', '광양중동', '광주전남혁신도시', '순천원도심', '여수학동',
       '전남도청', '조례', '하당신도심', '군산수송동조촌동', '군산원도심', '익산역', '전북혁신도시',
       '전주동부', '전주서부', '전주서부신시가지', '광양사거리', '노형오거리', '금산인삼국제시장',
       '논산시외버스터미널', '당진시청', '두정', '백석', '서산터미널', '아산온양', '천안시청', '천안역',
       '천안종합버스터미널', '태안터미널', '오창호수공원', '용담동우체국', '제천역', '제천중앙',
       '청주고속버스터미널', '청주지방법원', '충북혁신도시', '충주연수칠금', '충주자유시장'], dtype=object)

In [149]:
n_columns =  ['광역상권', '상권명', '임차인업종대분류', '임차인업종소분류', '전용면적', '전용면적(호)', '임차인별면적합계', '조사층', '건물주용도', '표본구분', '건물구조명','제3월계약임대료_보증금','제3월계약임대료_월세','제3월시장임대료_보증금','제3월시장임대료_월세', '제3월관리비실비총액']

s_store_2026_2 = s_store_2026_2[n_columns]
b_store_2026_2 = b_store_2026_2[n_columns]

In [150]:
s_store_2026_2 = s_store_2026_2[s_store_2026_2['상권명'] == '뚝섬']
b_store_2026_2 = b_store_2026_2[b_store_2026_2['상권명'] == '뚝섬']

In [151]:
display(s_store_2026_2.head(2), b_store_2026_2.head(2))

,광역상권,상권명,임차인업종대분류,임차인업종소분류,전용면적,전용면적(호),임차인별면적합계,조사층,건물주용도,표본구분,건물구조명,제3월계약임대료_보증금,제3월계약임대료_월세,제3월시장임대료_보증금,제3월시장임대료_월세,제3월관리비실비총액
653,4.기타,뚝섬,I,561,2,2,2,1,4,6,12,6,6,6,6,1
654,4.기타,뚝섬,I,562,4,2,2,-1,4,6,11,5,5,5,5,1

,광역상권,상권명,임차인업종대분류,임차인업종소분류,전용면적,전용면적(호),임차인별면적합계,조사층,건물주용도,표본구분,건물구조명,제3월계약임대료_보증금,제3월계약임대료_월세,제3월시장임대료_보증금,제3월시장임대료_월세,제3월관리비실비총액
1731,4.기타,뚝섬,G,478,5,4,4,-1,3,2,21,4,4,6,5,1
1732,4.기타,뚝섬,I,561,5,2,2,1,3,2,21,6,6,6,6,1

In [152]:
print(s_store_2026_2.shape, b_store_2026_2.shape)

(64, 16) (215, 16)